# Marvish Chandra

class individualDrugs:

    def __init__(self,drugName,chemicalFormula,useCase,drugClassification):
        self.drugName = drugName
        self.chemicalFormula = chemicalFormula
        self.useCase = useCase
        self.drugClassification = drugClassification

def hundredInfo():
        firstdrug = individualDrugs("Albuterol","C13H21NO3","beta-adrenergic agonist used in the treatment of asthma and chronic obstructive pulmonary disease (COPD)","Phenylethanolamines")
        print(vars(firstdrug))
        seconddrug = individualDrugs("Amlodipine","C20H25ClN2O5","second generation calcium channel blocker that is used in the therapy of hypertension and angina pectoris","Calcium channel blockers")
        print(vars(seconddrug))
        thirddrug = individualDrugs("Alendronate","C4H13NO7P2","used to treat osteoporosis caused by menopause, steroid use, or gonadal failure","Bisphosphonate")
        print(vars(thirddrug))
        fourthdrug = individualDrugs("Allopurinol","C5H4N4O"," a xanthine oxidase inhibitor and a widely used medication for gout","Xanthinine Oxidase Inhibitor")
        print(vars(fourthdrug))
        fifthdrug = individualDrugs("Alprazolam","C17H13ClN4"," used to treat anxiety disorders, panic disorders, and anxiety caused by depression.","Benzodiazepine")
        print(vars(fifthdrug))
        sixthdrug = individualDrugs("Amitriptyline","C20H23N","a tricyclic antidepressant used to treat symptoms of depression (FDA approved), and amitriptyline is used off-label for insomnia, migraine prevention, ADHD, eating disorders, bipolar disorder, anxiety, psychotic disorders, and some types of pain","Tricyclic Antidepressant")
        print(vars(sixthdrug))
        seventhdrug = individualDrugs("Amoxicillin-Clavulanate","C16H19N3O5S","an oral antibiotic widely used in the treatment of mild-to-moderate bacterial infections including sinusitis, bronchitis, otitis media, cellulitis and community acquired pneumonia","Aminopenicillins")
        print(vars(seventhdrug))
        eighthdrug = individualDrugs("Amoxicillin","C16H19N3O5S","used to treat mild to moderate infections","Aminopenicillins")
        print(vars(eighthdrug))
        ninthdrug = individualDrugs("Amphetamine and dextroamphetamine XR","C9H13N","central nervous system stimulants that affect chemicals in the brain and nerves that contribute to hyperactivity and impulse control","Attention Deficit Hyperactivity Disorder (ADHD) control")
        print(vars(ninthdrug))
        tenthdrug = individualDrugs("Atenolol","C14H22N2O3","used to treat angina (chest pain) and hypertension (high blood pressure)","Beta-Blocker")
        print(vars(tenthdrug))
        eleventhdrug = individualDrugs("Atorvastatin","C33H35FN2O5","cholesterol lowering agent","HMG-CoA reductase inhibitors (statins)")
        print(vars(eleventhdrug))
        twelvthdrug = individualDrugs("Azithromycin", "C38H72N2O12","a semisynthetic macrolide antibiotic which is commonly used for a wide variety of mild-to-moderate bacterial infections","Macrolides")
        print(vars(twelvthdrug))
        thirteenthdrug = individualDrugs("Benazepril and amlodipine","C44H53ClN4O10","a combination medicine used to treat high blood pressure (hypertension).","Combination Med;ACE Inhibitor;Calcium Channel Blocker")
        print(vars(twelvthdrug))
        fourteenthdrug = individualDrugs("Carisoprodol","C12H24N2O4","used together with rest and physical therapy to treat skeletal muscle conditions such as pain or injury","Muscle Relaxant")
        print(vars(fourteenthdrug))
        fifteenthdrug = individualDrugs("Carvedilol","C24H26N2O4","used to treat heart failure and hypertension (high blood pressure)","Beta-Blocker")
        print(vars(fifteenthdrug))
        sixteenthdrug = individualDrugs("Cefdinir","C14H13N5O5S2","a cephalosporin (SEF a low spor in) antibiotic that is used to treat many different types of infections caused by bacteria","Cephalosporin")
        print(vars(sixteenthdrug))
        seventeenthdrug = individualDrugs("Celecoxib","C17H14F3N3O2S","used to treat pain or inflammation caused by many conditions such as arthritis, ankylosing spondylitis, and menstrual pain","Cox-2 Inhibitor")
        print(vars(seventeenthdrug))
        eightteenthdrug = individualDrugs("Cephalexin","C16H17N3O4S","used to treat infections caused by bacteria, including upper respiratory infections, ear infections, skin infections, urinary tract infections and bone infections","First generation cephalosporins")
        print(vars(eightteenthdrug))
        ninteenthdrug = individualDrugs("Ciprofloxacin","C17H18FN3O3","a fluoroquinolone (flor-o-KWIN-o-lone) antibiotic, it is used to treat different types of bacterial infections","Quinolone")
        print(vars(ninteenthdrug))
        twentiethdrug = individualDrugs("Citalopram","C20H21FN2O","prescription medicine used in adults to treat depression","Selective Seratonin Receptor Inhibitor")
        print(vars(twentiethdrug))
        twentyfirstdrug = individualDrugs("Clonazepam","C15H10ClN3O3","used to treat certain seizure disorders (including absence seizures or Lennox-Gastaut syndrome) in adults and children","Benzodiazepine")
        print(vars(twentyfirstdrug))
        twentyseconddrug = individualDrugs("Clonidine HCl","C9H10Cl3N3","lowers blood pressure by decreasing the levels of certain chemicals in your blood","Alpha 2 Agonist")
        print(vars(twentyseconddrug))
        twentyfourthdrug = individualDrugs("Clopidogrel","C16H16ClNO2S","used to lower your risk of having a stroke, blood clot, or serious heart problem after you've had a heart attack, severe chest pain (angina), or circulation problems","Antiplatelet Agent")
        print(vars(twentyfourthdrug))
        twentyfifthdrug = individualDrugs("Premarin (conjugated estrogens)","C18H19NaO5S","used to treat menopause symptoms such as hot flashes and vaginal changes, and to prevent osteoporosis (bone loss) in menopausal women","Estrogen Derivative")
        print(vars(twentyfifthdrug))
        twentysixthdrug = individualDrugs("Cyclobenzaprine","C20H21N","used together with rest and physical therapy to treat skeletal muscle conditions such as pain or injury","Skeletal Muscle Relaxant")
        print(vars(twentysixthdrug))
        twentyseventhdrug = individualDrugs("Diazepam","C16H13ClN2O","used to treat anxiety disorders, or alcohol withdrawal symptoms.","Benzodiazepine")
        print(vars(twentyseventhdrug))
        twentyeighthdrug = individualDrugs("Diclofenac sodium","C14H10Cl2NNaO2"," used to treat mild to moderate pain, or signs and symptoms of osteoarthritis or rheumatoid arthritis","Non-Steroidal Anti-Inflammatory Drug (NSAID)")
        print(vars(twentyeighthdrug))
        twentyninthdrug = individualDrugs("Yaz (drospirenone and ethinyl estradiol)","C44H54O5","a combination oral contraceptive indicated for prevention of pregnancy in women who elect to use an oral contraceptive","Oral Contraceptive")
        print(vars(twentyninthdrug))
        thirtythdrug = individualDrugs("Duloxetine","C18H19NOS","used to treat major depressive disorder in adults","Serotonin/Norephinephrine Reuptake Inhibitor")
        print(vars(thirtythdrug))
        thirtyfirstdrug = individualDrugs("Doxycycline hyclate","C22H24N2O9","used to treat many different bacterial infections of the skin, intestines, respiratory tract, urinary tract, genitals, lymph nodes, and other body systems","Tetracycline")
        print(vars(thirtyfirstdrug))
        thirtysecondrug = individualDrugs("Enalapril","C20H28N2O5","used alone or in combination with other medications to treat high blood pressure in adults and children at least 1 month old","ACE-Inhibitor")
        print(vars(thirtysecondrug))
        thirtythirddrug = individualDrugs("Escitalopram","C20H21FN2O","used to treat major depressive disorder in adults and adolescents at least 12 years old","Selective serotonin reuptake inhibitors")
        print(vars(thirtythirddrug))
        thirtyfourthdrug = individualDrugs("Esomeprazole","C17H19N3O3S"," used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome","Proton Pump Inhibitor")
        print(vars(thirtyfourthdrug))
        thirtyfifthdrug = individualDrugs("Ezetimibe","C24H21F2NO3","used to lower cholesterol in people who have high blood cholesterol","2-Azetidinone")
        print(vars(thirtyfifthdrug))
        thirtysixthdrug = individualDrugs("Fenofibrate","C20H21ClO4","medicine used with a cholesterol-reducing diet to lower high cholesterol and high triglyceride (fatty acid) levels in the blood","Cholesterol Lowering Agent")
        print(vars(thirtysixthdrug))
        thirtyseventhdrug = individualDrugs("Fexofenadine","C32H39NO4","an antihistamine that may be used to treat allergy symptoms (including hay fever) in adults and children","Antihistamine")
        print(vars(thirtyseventhdrug))
        thirtyeighthdrug = individualDrugs("Fluconozole","C13H12F2N6O","a prescription azole antifungal medication that may be used to treat serious fungal or yeast infections including those that affect the vagina, mouth or throat, lungs, bladder, or blood","Antifungal")
        print(vars(thirtyeighthdrug))
        thirtyninthdrug = individualDrugs("Fluoxetine Hydrochloride","C17H19ClF3NO","a selective serotonin reuptake inhibitor (SSRI) antidepressant","Selective Seratonin Receptor Inhibitor")
        print(vars(thirtyninthdrug))
        fortythdrug = individualDrugs("Fluticasone and salmeterol inhaler","C50H68F3NO9S","a steroid and bronchodilator combination medicine that is used to prevent asthma attacks","Combination Med;Oral Corticosteroid;Long Acting Beta2-agonist")
        print(vars(fortythdrug))
        fortyfirstdrug = individualDrugs("Fluticasone nasal spray","C25H31F3O5S","a steroid medicine that is used to treat nasal congestion, sneezing, runny nose, and itchy or watery eyes caused by seasonal or year-round allergies","Nasal Corticosteroid")
        print(vars(fortyfirstdrug))
        fortyseconddrug = individualDrugs("Folic acid","C19H19N7O6"," a B vitamin supplement that may be used to prevent and treat folate deficiency (low blood levels of folate) that can cause megaloblastic anemia","Vitamin")
        print(vars(fortyseconddrug))
        fortythirddrug = individualDrugs("Furosemide", "C12H11ClN2O5S", " a loop diuretic used to treat fluid retention (edema) in people with congestive heart failure, liver disease, or a kidney disorder such as nephrotic syndrome","Loop diuretics")
        print(vars(fortythirddrug))
        fortyforthdrug = individualDrugs("Gabapentin", "C9H17NO2","unique anticonvulsant that is used as adjunctive therapy in management of epilepsy and for neuropathic pain syndromes","Gamma-aminobutyric acid analogs")
        print(vars(fortyforthdrug))
        fortyfifthdrug = individualDrugs("Glimepiride","C24H34N4O5S","an oral diabetes medicine that is used together with diet and exercise to improve blood sugar control in adults with type 2 diabetes mellitus", "Anti-Diabetic")
        print(vars(fortyfifthdrug))
        fortysixthdrug = individualDrugs("Glyburide","C23H28ClN3O5S","used together with diet and exercise to improve blood sugar control in adults with type 2 diabetes mellitus","Sulfonylurea")
        print(vars(fortysixthdrug))
        fortyseventhdrug = individualDrugs("Glipizide","C23H28ClN3O5S","used together with diet and exercise to improve blood sugar control in adults with type 2 diabetes mellitus","Sulfonylurea")
        print(vars(fortyseventhdrug))
        fortyeighthdrug = individualDrugs("Hydrochlorothiazide", "C7H8ClN3O4S2","for clinical use in adjunctive therapy in edema that is associated with chronic heart failure (CHF), hepatic cirrhosis, corticosteroids, and estrogen therapy","Thiazide diuretics")
        print(vars(fortyeighthdrug))
        fortyninthdrug = individualDrugs("Hydrocodone and acetaminophen","C4H9NO2","used to treat fluid retention (edema) in people with congestive heart failure, cirrhosis of the liver, or kidney disorders, or edema caused by taking steroids or estrogen", "Narcotic Analgesic")
        print(vars(fortyninthdrug))
        fiftythdrug = individualDrugs("Ibuprofen", "C13H18O2", "used for treatment of mild-to-moderate forms of joint pain and arthritis from trauma, osteoarthritis or rheumatoid arthritis","Glucocorticoids")
        print(vars(fiftythdrug))
        fiftyfirstdrug = individualDrugs("Lantus (insulin glargine)","C267H404N72O78S6","used to improve blood sugar control in adults and children with diabetes mellitus","Insulin")
        print(vars(fiftyfirstdrug))
        fiftyseconddrug = individualDrugs("Isosorbide mononitrate","C6H9NO6","used to prevent angina attacks (chest pain)","Vasiodilator")
        print(vars(fiftyseconddrug))
        fiftythirddrug = individualDrugs("Lansoprazole","C16H14F3N3O2S","used to treat and prevent stomach and intestinal ulcers, erosive esophagitis (damage to the esophagus from stomach acid), and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome","Proton Pump Inhibitor")
        print(vars(fiftythirddrug))
        fiftyfourthdrug = individualDrugs("Levofloxacin","C18H20FN3O4","usually only used for bacterial infections that cannot be treated with safer antibiotics","Quinolone")
        print(vars(fiftyfourthdrug))
        fiftyfifthdrug = individualDrugs("Levothyroxine sodium","C15H10I4NNaO4","used in adults and children to treat hypothyroidism (underactive thyroid - a condition where the thyroid gland does not produce enough thyroid hormone)","Thyroid Hormone Replacement")
        print(vars(fiftyfifthdrug))
        fiftysixthdrug = individualDrugs("Synthroid","C15H11I4NO4","a thyroid medicine that replaces a hormone normally produced by your thyroid gland to regulate the body's energy and metabolism","Thyroid Hormone Replacement")
        print(vars(fiftysixthdrug))
        fiftyseventhdrug = individualDrugs("Lisinopril and Hydrochlorothiazide","C28H39ClN6O9S2"," a combination medicine used to treat hypertension (high blood pressure)","Combination Med;ACE Inhibitor;Diuretic")
        print(vars(fiftyseventhdrug))
        fiftyeighthdrug = individualDrugs("Lorazepam","C15H10Cl2N2O2","used in adults and children at least 12 years old to treat anxiety disorders","Benzodiazepine")
        print(vars(fiftyeighthdrug))
        fiftyninthdrug = individualDrugs("Losartan","C22H23ClN6O"," used alone or in combination with other medications to treat high blood pressure in adults and children at least 6 years old","Angiotensin Receptor Blocker")
        print(vars(fiftyninthdrug))
        sixtythdrug = individualDrugs("Lovastatin","C24H36O5","used to lower the risk of stroke, heart attack, and other heart complications in adults with diabetes, coronary heart disease, or other risk factors","HMG-CoA reductase Inhibitor")
        print(vars(sixtythdrug))
        sixtyfirstdrug = individualDrugs("Meloxicam","C14H13N3O4S2","used to relieve pain, tenderness, swelling, and stiffness caused by osteoarthritis (arthritis caused by a breakdown of the lining of the joints) and rheumatoid arthritis (arthritis caused by swelling of the lining of the joints)","Non-Steroidal Anti-Inflammatory Drug (NSAID)")
        print(vars(sixtyfirstdrug))
        sixtysecondrug = individualDrugs("Metformin HCl","C4H12ClN5","antidiabetic agent that manages high blood sugar levels in type 2 diabetes patients","Biguanide")
        print(vars(sixtysecondrug))
        sixtythirddrug = individualDrugs("Methylprednisone","C22H28O5","used to treat many different inflammatory conditions such as arthritis, lupus, psoriasis, ulcerative colitis, allergic disorders, gland (endocrine) disorders, and conditions that affect the skin, eyes, lungs, stomach, nervous system, or blood cells","Corticosteroid")
        print(vars(sixtythirddrug))
        sixtyfourthdrug = individualDrugs("Metoprolol succinate XL","C34H56N2O10","used to treat angina (chest pain) and hypertension (high blood pressure)","Beta-Blocker")
        print(vars(sixtyfourthdrug))
        sixtyfifthdrug = individualDrugs("Metoprolol tartrate","C34H56N2O12","a beta-adrenergic blocker indicated for the treatment of: Hypertension, to lower blood pressure, angina pectoris, myocardial infarction","Beta-Blocker")
        print(vars(sixtyfifthdrug))
        sixtysixthdrug = individualDrugs("Mometasone","C22H28Cl2O4","reduces the actions of chemicals in the body that cause inflammation","Corticosteroid")
        print(vars(sixtysixthdrug))
        sixtyseventhdrug = individualDrugs("Montelukast","C35H36ClNO3S","helps to reduce inflammation and may be used to prevent asthma attacks in adults and children at least 2 years old","Leukotriene Receptor Antagonist")
        print(vars(sixtyseventhdrug))
        sixtyeighthdrug = individualDrugs("Naproxen","C14H14O3","used to treat pain or inflammation caused by conditions such as arthritis, ankylosing spondylitis, tendinitis, bursitis, gout, or menstrual cramps","Non-Steroidal Anti-Inflammatory Drug (NSAID)")
        print(vars(sixtyeighthdrug))
        sixtyninthdrug = individualDrugs("Omeprazole","C17H19N3O3S","used to treat excess stomach acid in conditions such as non cancerous stomach ulcers, gastroesophageal reflux disease (GERD), active duodenal ulcer, Zollinger-Ellison syndrome and erosive esophagitis","Proton Pump Inhibitor")
        print(vars(sixtyninthdrug))
        seventythdrug = individualDrugs("Oxycodone and acetaminophen","C26H31ClN2O6","a combination medication for moderate to severe pain","Narcotic Analgesic")
        print(vars(seventythdrug))
        seventyfirstdrug = individualDrugs("Pantoprazole","C16H15F2N3O4S","a proton pump inhibitor that decreases the amount of acid produced in the stomach","Proton Pump Inhibitor")
        print(vars(seventyfirstdrug))
        seventyseconddrug = individualDrugs("Paroxetine","C19H20FNO3","used to treat depression, including major depressive disorder","Selective Serotonin Receptor Inhibitor")
        print(vars(seventyseconddrug))
        seventythirddrug = individualDrugs("Pioglitazone","C19H20N2O3S","used together with diet and exercise to improve blood sugar control in adults with type 2 diabetes mellitus","Thiazolidinedione")
        print(vars(seventythirddrug))
        seventyfourthdrug = individualDrugs("Potassium Chloride","KCl","used to prevent or to treat low blood levels of potassium (hypokalemia)","Electrolyte Supplement")
        print(vars(seventyfourthdrug))
        seventyfifthdrug = individualDrugs("Pravastatin","C23H36O7","used together with diet to lower blood levels of bad cholesterol (low-density lipoprotein, or LDL), to increase levels of good cholesterol (high-density lipoprotein, or HDL), and to lower triglycerides (a type of fat in the blood)","HMG-CoA reductase Inhibitor")
        print(vars(seventyfifthdrug))
        seventysixthdrug = individualDrugs("Prednisone","C21H26O5","used to treat allergic disorders, skin conditions, ulcerative colitis, Crohn’s disease, arthritis, lupus, psoriasis, asthma, chronic obstructive pulmonary disease (COPD) and many more conditions","Oral Corticosteroid")
        print(vars(seventysixthdrug))
        seventyseventhdrug = individualDrugs("Pregabalin","C8H17NO2","used to treat pain caused by fibromyalgia, or nerve pain in people with diabetes (diabetic neuropathy), herpes zoster (post-herpetic neuralgia), or spinal cord injury","Gamma Aminobutyric Acid")
        print(vars(seventyseventhdrug))
        seventyeighthdrug = individualDrugs("Promethazine","C17H20N2S","used to treat allergy symptoms such as itching, runny nose, sneezing, itchy or watery eyes, hives, and itchy skin rashes","Antiemetic")
        print(vars(seventyeighthdrug))
        seventyninthdrug = individualDrugs("Quetiapine","C21H25N3O2S","used to treat schizophrenia in adults and children who are at least 13 years old","Antipsychotic")
        print(vars(seventyninthdrug))
        eightythdrug = individualDrugs("Quetiapine","C21H25N3O2S","used to treat schizophrenia in adults and children who are at least 13 years old","Antipsychotic")
        print(vars(eightythdrug))
        eightyfirstdrug = individualDrugs("Ranitidine","C13H22N4O3S","used to treat and prevent ulcers in the stomach and intestines","H2-antagonist")
        print(vars(eightyfirstdrug))
        eightyseconddrug = individualDrugs("Rosuvastatin","C22H28FN3O6S","a prescription medication used to treat high cholesterol and prevent heart attacks and strokes","HMG-CoA reductase Inhibitor")
        print(vars(eightyseconddrug))
        eightythirddrug = individualDrugs("Sertraline HCl","C17H18Cl3N","a medication used for depression, panic disorders, obsessive-compulsive disorder (OCD), social anxiety disorder (SAD), post-traumatic stress disorder (PTSD), and premenstrual dysphoric disorder (PMDD)","Selective Serotonin Receptor Inhibitor")
        print(vars(eightythirddrug))
        eightyfourthdrug = individualDrugs("Viagra (sildenafil HCl)","C28H38N6O11S","used to treat erectile dysfunction (impotence) in men","Phophodiesterase-5 Inhibitor")
        print(vars(eightyfourthdrug))
        eightyfifthdrug = individualDrugs("Simvastatin and ezetimibe","C49H59F2NO8"," a combination medicine that is used to lower blood levels of bad cholesterol (low-density lipoprotein, or LDL), to increase levels of good cholesterol (high-density lipoprotein, or HDL), and to lower triglycerides (a type of fat in the blood)","Combo Med;HMG-CoA Reductase Inhibitor and 2-azetidinone")
        print(vars(eightyfifthdrug))
        eightysixthdrug = individualDrugs("Simvastatin","C25H38O5","used to lower blood levels of bad cholesterol (low-density lipoprotein, or LDL), to increase levels of good cholesterol (high-density lipoprotein, or HDL), and to lower triglycerides (a type of fat in the blood","HMG-CoA reductase Inhibitor")
        print(vars(eightysixthdrug))
        eightyseventhdrug = individualDrugs("Spironolactone","C24H32O4S","used to treat heart failure, high blood pressure (hypertension), or hypokalemia (low potassium levels in the blood)","Diuretic")
        print(vars(eightyseventhdrug))
        eightyeighthdrug = individualDrugs("Sulfamethoxazole and trimethoprim DS","C10H11N3O3S "," combination antibiotic used to treat ear infections, urinary tract infections, bronchitis, traveler's diarrhea, shigellosis, and Pneumocystis jiroveci pneumonia","Combo Med;Sulfonamide and Trimethoprim")
        print(vars(eightyeighthdrug))
        eightyninthdrug = individualDrugs("Tamsulosin","C20H28N2O5S","used in men to treat the symptoms of an enlarged prostate (benign prostatic hyperplasia or BPH) which include difficulty urinating (hesitation, dribbling, weak stream, and incomplete bladder emptying), painful urination, and urinary frequency and urgency","Alpha1-Blocker")
        print(vars(eightyninthdrug))
        ninetythdrug = individualDrugs("Temezepam","C16H13ClN2O2","used short term to treat insomnia (trouble falling or staying asleep)","Benzodiazepine")
        print(vars(ninetythdrug))
        ninetyonedrug = individualDrugs("Topiramate","C12H21NO8S","used alone or with other medications to treat certain types of seizures in adults and children at least 2 years old","Anti-Convulsant")
        print(vars(ninetyonedrug))
        ninetyseconddrug = individualDrugs("Tramadol","C16H25NO2","an opioid agonist that may be used to treat moderate to moderately severe chronic pain in adults","Non-Narcotic Analgesic")
        print(vars(ninetyseconddrug))
        ninetythirddrug = individualDrugs("Triamcinolone Ace topical","C21H27FO6","used to treat many different conditions such as allergic disorders, skin conditions, ulcerative colitis, arthritis, lupus, psoriasis, or breathing disorders","Topical Corticosteroid")
        print(vars(ninetythirddrug))
        ninetyfourthdrug = individualDrugs("Trazodone HCl","C19H23Cl2N5O","an antidepressant that belongs to a group of drugs called serotonin receptor antagonists and reuptake inhibitors","Serotonin Reuptake Inhibitor")
        print(vars(ninetyfourthdrug))
        ninetyfifthdrug = individualDrugs("Triamterene and hydrochlorothiazide","C19H19ClN10O4S2","a combination medicine that is used to treat fluid retention (edema) and high blood pressure (hypertension)","Combo Med;Thiazide and Potassium Sparing Diuretic")
        print(vars(ninetyfifthdrug))
        ninetysixthdrug = individualDrugs("Valaciclovir","C13H20N6O4","used to treat cold sores in children who are at least 12 years old, or chickenpox in children who are at least 2 years old","Antiviral")
        print(vars(ninetysixthdrug))
        ninetyseventhdrug = individualDrugs("Valsartan","C24H29N5O3","an angiotensin II receptor blocker (ARB) that may be used to treat high blood pressure or reduce the risk of being admitted to the hospital if you have heart failure","Angiotensin Receptor Blocker")
        print(vars(ninetyseventhdrug))
        ninetyeighthdrug = individualDrugs("Venlafaxine XR","C17H28ClNO2","used in adults to treat major depressive disorder","Serotonin/Norepinephrine Reuptake Inhibitor")
        print(vars(ninetyeighthdrug))
        ninetyninethdrug = individualDrugs("Verapamil SR","C27H39ClN2O4","used to treat hypertension (high blood pressure), angina (chest pain), and certain heart rhythm disorders","Calcium Channel Blocker")
        print(vars(ninetyninethdrug))
        hundredthdrug = individualDrugs("Zolpidem","C19H21N3O","used in adults to treat insomnia","Hypnotic")
        print(vars(hundredthdrug))

hundredInfo()