# Marvish Chandra

class individualDrugs:

    def __init__(self,drugName,chemicalFormula,useCase,drugClassification):
        self.drugName = drugName
        self.chemicalFormula = chemicalFormula
        self.useCase = useCase
        self.drugClassification = drugClassification

    firstdrug = individualDrugs("Albuterol","C13H21NO3","beta-adrenergic agonist used in the treatment of asthma and chronic obstructive pulmonary disease (COPD)","Phenylethanolamines")
    print(firstdrug)
    seconddrug = individualDrugs("Amlodipine","C20H25ClN2O5","second generation calcium channel blocker that is used in the therapy of hypertension and angina pectoris","Calcium channel blockers")
    print(seconddrug)
    thirddrug = individualDrugs("Alendronate","C4H13NO7P2","used to treat osteoporosis caused by menopause, steroid use, or gonadal failure","Bisphosphonate")
    print(thirddrug)
    fourthdrug = individualDrugs("Allopurinol","C5H4N4O"," a xanthine oxidase inhibitor and a widely used medication for gout","Xanthinine Oxidase Inhibitor")
    print(fourthdrug)
    fifthdrug = individualDrugs("Alprazolam","C17H13ClN4"," used to treat anxiety disorders, panic disorders, and anxiety caused by depression.","Benzodiazepine")
    print(fifthdrug)
    sixthdrug = individualDrugs("Amitriptyline","C20H23N","a tricyclic antidepressant used to treat symptoms of depression (FDA approved), and amitriptyline is used off-label for insomnia, migraine prevention, ADHD, eating disorders, bipolar disorder, anxiety, psychotic disorders, and some types of pain","Tricyclic Antidepressant")
    print(sixthdrug)
    seventhdrug = individualDrugs("Amoxicillin-Clavulanate","C16H19N3O5S","an oral antibiotic widely used in the treatment of mild-to-moderate bacterial infections including sinusitis, bronchitis, otitis media, cellulitis and community acquired pneumonia","Aminopenicillins")
    print(seventhdrug)
    eighthdrug = individualDrugs("Amoxicillin","C16H19N3O5S","used to treat mild to moderate infections","Aminopenicillins")
    print(eighthrug)
    ninthdrug = individualDrugs("Amphetamine and dextroamphetamine XR","C9H13N","central nervous system stimulants that affect chemicals in the brain and nerves that contribute to hyperactivity and impulse control","Attention Deficit Hyperactivity Disorder (ADHD) control")
    print(ninthdrug)
    tenthdrug = individualDrugs("Atenolol","C14H22N2O3","used to treat angina (chest pain) and hypertension (high blood pressure)","Beta-Blocker")
    print(tenthdrug)
    eleventhdrug = individualDrugs("Atorvastatin","C33H35FN2O5","cholesterol lowering agent","HMG-CoA reductase inhibitors (statins)")
    print(eleventhdrug)
    twelvthdrug = individualDrugs("Azithromycin", "C38H72N2O12","a semisynthetic macrolide antibiotic which is commonly used for a wide variety of mild-to-moderate bacterial infections","Macrolides")
    print(twelvthdrug)
    thirteenthdrug = individualDrugs("Benazepril and amlodipine","C44H53ClN4O10","a combination medicine used to treat high blood pressure (hypertension).","Combination Med;ACE Inhibitor;Calcium Channel Blocker")
    print(thirteenthdrug)
    fourteenthdrug = individualDrugs("Carisoprodol","C12H24N2O4","used together with rest and physical therapy to treat skeletal muscle conditions such as pain or injury","Muscle Relaxant")
    print(fourteenthdrug)
    fifteenthdrug = individualDrugs("Carvedilol","C24H26N2O4","used to treat heart failure and hypertension (high blood pressure)","Beta-Blocker")
    print(fifteenthdrug)
    sixteenthdrug = individualDrugs("Cefdinir","C14H13N5O5S2","a cephalosporin (SEF a low spor in) antibiotic that is used to treat many different types of infections caused by bacteria","Cephalosporin")
    print(sixteenthdrug)
    seventeenthdrug = individualDrugs("Celecoxib","C17H14F3N3O2S","used to treat pain or inflammation caused by many conditions such as arthritis, ankylosing spondylitis, and menstrual pain","Cox-2 Inhibitor")
    print(seventeenthdrug)
    eightteenthdrug = individualDrugs("Cephalexin","C16H17N3O4S","used to treat infections caused by bacteria, including upper respiratory infections, ear infections, skin infections, urinary tract infections and bone infections","First generation cephalosporins")
    print(eightteenthdrug)
    ninteenthdrug = individualDrugs("Ciprofloxacin","C17H18FN3O3","a fluoroquinolone (flor-o-KWIN-o-lone) antibiotic, it is used to treat different types of bacterial infections","Quinolone")
    print(ninteenthdrug)
    twentiethdrug = individualDrugs("Citalopram","C20H21FN2O","prescription medicine used in adults to treat depression","Selective Seratonin Receptor Inhibitor")
    print(twentiethdrug)
    twentyfirstdrug = individualDrugs("Clonazepam","C15H10ClN3O3","used to treat certain seizure disorders (including absence seizures or Lennox-Gastaut syndrome) in adults and children","Benzodiazepine")
    print(twentyfirstdrug)
    twentyseconddrug = individualDrugs("Clonidine HCl","C9H10Cl3N3","lowers blood pressure by decreasing the levels of certain chemicals in your blood","Alpha 2 Agonist")
    print(twentyseconddrug)
    twentyfourthdrug = individualDrugs("Clopidogrel","C16H16ClNO2S","used to lower your risk of having a stroke, blood clot, or serious heart problem after you've had a heart attack, severe chest pain (angina), or circulation problems","Antiplatelet Agent")
    print(twentyfourthdrug)
    twentyfifthdrug = individualDrugs("Premarin (conjugated estrogens)","C18H19NaO5S","used to treat menopause symptoms such as hot flashes and vaginal changes, and to prevent osteoporosis (bone loss) in menopausal women","Estrogen Derivative")
    print(twentyfifthdrug)
    twentysixthdrug = individualDrugs("Cyclobenzaprine","C20H21N","used together with rest and physical therapy to treat skeletal muscle conditions such as pain or injury","Skeletal Muscle Relaxant")
    print(twentysixthdrug)
    twentyseventhdrug = individualDrugs("Diazepam","C16H13ClN2O","used to treat anxiety disorders, or alcohol withdrawal symptoms.","Benzodiazepine")
    print(twentyseventhdrug)
    twentyeighthdrug = individualDrugs("Diclofenac sodium","C14H10Cl2NNaO2"," used to treat mild to moderate pain, or signs and symptoms of osteoarthritis or rheumatoid arthritis","Non-Steroidal Anti-Inflammatory Drug (NSAID)")
    print(twentyeighthdrug)
    twentyninthdrug = individualDrugs("Yaz (drospirenone and ethinyl estradiol)","C44H54O5","a combination oral contraceptive indicated for prevention of pregnancy in women who elect to use an oral contraceptive","Oral Contraceptive")
    print(twentyninthdrug)
    thirtythdrug = individualDrugs("Duloxetine","C18H19NOS","used to treat major depressive disorder in adults","Serotonin/Norephinephrine Reuptake Inhibitor")
    print(thirtythdrug)
    thirtyfirstdrug = individualDrugs("Doxycycline hyclate","C22H24N2O9","used to treat many different bacterial infections of the skin, intestines, respiratory tract, urinary tract, genitals, lymph nodes, and other body systems","Tetracycline")
    print(thirtyfirstdrug)
    thirtysecondrug = individualDrugs("Enalapril","C20H28N2O5","used alone or in combination with other medications to treat high blood pressure in adults and children at least 1 month old","ACE-Inhibitor")
    print(thirtysecondrug)
    thirtythirddrug = individualDrugs("Escitalopram","C20H21FN2O","used to treat major depressive disorder in adults and adolescents at least 12 years old","Selective serotonin reuptake inhibitors")
    print(thirtythirddrug)
    thirtyfourthdrug = individualDrugs("Esomeprazole","C17H19N3O3S"," used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome","Proton Pump Inhibitor")
    print(thirtyfourthdrug)
    thirtyfifthdrug = individualDrugs("Ezetimibe","C24H21F2NO3","used to lower cholesterol in people who have high blood cholesterol","2-Azetidinone")
    print(thirtyfifthdrug)
    thirtysixthdrug = individualDrugs("Fenofibrate","C20H21ClO4","medicine used with a cholesterol-reducing diet to lower high cholesterol and high triglyceride (fatty acid) levels in the blood","Cholesterol Lowering Agent")
    print(thirtysixthdrug)
    thirtyseventhdrug = individualDrugs("Fexofenadine","C32H39NO4","an antihistamine that may be used to treat allergy symptoms (including hay fever) in adults and children","Antihistamine")
    print(thirtyseventhdrug)
    thirtyeighthdrug = individualDrugs("Fluconozole","C13H12F2N6O","a prescription azole antifungal medication that may be used to treat serious fungal or yeast infections including those that affect the vagina, mouth or throat, lungs, bladder, or blood","Antifungal")
    print(thirtyeighthdrug)
    thirtyninthdrug = individualDrugs("Fluoxetine Hydrochloride","C17H19ClF3NO","a selective serotonin reuptake inhibitor (SSRI) antidepressant","Selective Seratonin Receptor Inhibitor")
    print(thirtyninthdrug)
    fortythdrug = individualDrugs("Fluticasone and salmeterol inhaler","C50H68F3NO9S","a steroid and bronchodilator combination medicine that is used to prevent asthma attacks","Combination Med;Oral Corticosteroid;Long Acting Beta2-agonist")
    print(fortythdrug)
    fortyfirstdrug = individualDrugs("Fluticasone nasal spray","C25H31F3O5S","a steroid medicine that is used to treat nasal congestion, sneezing, runny nose, and itchy or watery eyes caused by seasonal or year-round allergies","Nasal Corticosteroid")
    print(fortyfirstdrug)
    fortyseconddrug = individualDrugs("Folic acid","C19H19N7O6"," a B vitamin supplement that may be used to prevent and treat folate deficiency (low blood levels of folate) that can cause megaloblastic anemia","Vitamin")
    print(fortyseconddrug)
    fortythirddrug = individualDrugs("Furosemide", "C12H11ClN2O5S", " a loop diuretic used to treat fluid retention (edema) in people with congestive heart failure, liver disease, or a kidney disorder such as nephrotic syndrome","Loop diuretics")
    print(fortythirddrug)
    fortyforthdrug = individualDrugs("Gabapentin", "C9H17NO2","unique anticonvulsant that is used as adjunctive therapy in management of epilepsy and for neuropathic pain syndromes","Gamma-aminobutyric acid analogs")
    print(fortyforthdrug)
    fortyfifthdrug = individualDrugs("Glimepiride","C24H34N4O5S","an oral diabetes medicine that is used together with diet and exercise to improve blood sugar control in adults with type 2 diabetes mellitus", "Anti-Diabetic")
    print(fortyfifthdrug)
    fortysixthdrug = individualDrugs("Glyburide","C23H28ClN3O5S","used together with diet and exercise to improve blood sugar control in adults with type 2 diabetes mellitus","Sulfonylurea")
    print(fortysixthdrug)
    fortyseventhdrug = individualDrugs("Glipizide","C23H28ClN3O5S","used together with diet and exercise to improve blood sugar control in adults with type 2 diabetes mellitus","Sulfonylurea")
    print(fortyseventhdrug)
    fortyeighthdrug = individualDrugs("Hydrochlorothiazide", "C7H8ClN3O4S2","for clinical use in adjunctive therapy in edema that is associated with chronic heart failure (CHF), hepatic cirrhosis, corticosteroids, and estrogen therapy","Thiazide diuretics")
    print(fortyeighthdrug)
    fortyninthdrug = individualDrugs("Hydrocodone and acetaminophen","C4H9NO2","used to treat fluid retention (edema) in people with congestive heart failure, cirrhosis of the liver, or kidney disorders, or edema caused by taking steroids or estrogen", "Narcotic Analgesic")
    print(fortyninthdrug)
    fiftythdrug = individualDrugs("Ibuprofen", "C13H18O2", "used for treatment of mild-to-moderate forms of joint pain and arthritis from trauma, osteoarthritis or rheumatoid arthritis","Glucocorticoids")
    print(fiftythdrug)




